[package]
name = "blog-api-with-rust"
version = "0.1.0"
authors = ["David Silva <srdavidsilva@gmail.com>"]
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
actix-web = "3"
mongodb = "1.2.1"